import type { Metadata } from 'next'
import '@/shared/styles/globals.css'
import '@/shared/styles/fonts.css'
import ReactQueryProvider from '@/shared/providers/ReactQueryProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <div className="flex justify-center">{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
