import type { Metadata } from 'next'
import '@/shared/styles/globals.css'
import '@/shared/styles/fonts.css'
import ReactQueryProvider from '@/shared/providers/ReactQueryProvider'
import { ModalProvider } from '@/shared/contexts/ModalContext'
import { StompProvider } from '@/shared/contexts/SocketContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <StompProvider>
            <ModalProvider>
              <div className="flex justify-center">{children}</div>
            </ModalProvider>
          </StompProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
