import type { Metadata } from 'next'
import '../globals.css'
import MainBottomNavigationBar from '@/shared/components/MainBottomNavigationBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="flex justify-center">
          <main className="flex h-svh w-full max-w-md flex-col">
            <section className="flex-1 overflow-auto">{children}</section>
            <MainBottomNavigationBar />
          </main>
        </div>
      </body>
    </html>
  )
}
